spring:
  application:
    name: management-center
#  webflux:
#    base-path: /${spring.application.name}
  mvc:
    pathmatch:
       matching-strategy: ANT_PATH_MATCHER
  #       国际化配置
  messages:
    basename: i18n.messages,i18n.commons
    encoding: UTF-8
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ${spring.application.name}
            instanceId: ${spring.application.name}
server:
  port: 9010
  servlet:
    context-path: /${spring.application.name}
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.fit2cloud.dao.handler
#监控，访问路径 {ip}:{port}/actuator
management:
  server:
    port: 9910

logging:
  file:
    path: @ce.log.base.dir@/${spring.application.name}

eureka:
  instance:
    metadata-map:
      order: 1
      name_zh-cn: 管理中心
      name_zh-tw: 管理中心
      name_en: Management Center
      basePath: ${server.servlet.context-path}/
      icon: shouye3
